// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2s-XrCNa1GfI-L624HjrBQU-5uuT7r7U',
    appId: '1:293741975649:web:a9824de06024b9d0137220',
    messagingSenderId: '293741975649',
    projectId: 'task-management-app-7f189',
    authDomain: 'task-management-app-7f189.firebaseapp.com',
    storageBucket: 'task-management-app-7f189.firebasestorage.app',
    measurementId: 'G-GNC4XR2NX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsO9gIbKRNNwDxwnsGH4g6fKYbzugy-4',
    appId: '1:293741975649:android:6c68c8182943d895137220',
    messagingSenderId: '293741975649',
    projectId: 'task-management-app-7f189',
    storageBucket: 'task-management-app-7f189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_uCD82UyJbYMHqxq614bxWZgjBPGMWl8',
    appId: '1:293741975649:ios:b7a624ec17d69753137220',
    messagingSenderId: '293741975649',
    projectId: 'task-management-app-7f189',
    storageBucket: 'task-management-app-7f189.firebasestorage.app',
    iosBundleId: 'com.example.taskManagmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_uCD82UyJbYMHqxq614bxWZgjBPGMWl8',
    appId: '1:293741975649:ios:b7a624ec17d69753137220',
    messagingSenderId: '293741975649',
    projectId: 'task-management-app-7f189',
    storageBucket: 'task-management-app-7f189.firebasestorage.app',
    iosBundleId: 'com.example.taskManagmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2s-XrCNa1GfI-L624HjrBQU-5uuT7r7U',
    appId: '1:293741975649:web:10ec82dfb7da5e28137220',
    messagingSenderId: '293741975649',
    projectId: 'task-management-app-7f189',
    authDomain: 'task-management-app-7f189.firebaseapp.com',
    storageBucket: 'task-management-app-7f189.firebasestorage.app',
    measurementId: 'G-Z997QESGFV',
  );
}
